language: java

os:
  - windows
  - linux
  - osx
dist: xenial

osx_image:
  - xcode6.4
  - xcode7.3
  - xcode8
  - xcode8.3
  - xcode9
  - xcode9.1
  - xcode9.2
  - xcode9.3
  - xcode9.4
  - xcode10
  - xcode10.1
  - xcode10.2
  - xcode10.3
  - xcode11
  - xcode11.1
  - xcode11.2
  - xcode11.3

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  allow_failures:
    - os:
      - osx
      - windows

before_install:
  - chmod +x ./gradlew

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL