# Default Configuration (written by PatrickKR, on Mar 24, 2020)
# Please do not remove the comments since it is used by vector command.

# Sets item to use for this plugin
# This directly translates to 'Material' in Spigot.
# If you are not familiar with it, DO NOT CHANGE.
vector-item: BLAZE_ROD

# Sets whether to use both hands or not.
# If true, players can select entity with right click and set velocity any time using left click.
# If false, players can both select entity and set velocity with right click.
use-both-hands: false

# Sets whether to set velocity single time or multiple times.
# If true, players can set velocity once after selecting entity.
# If false, players can set velocity multiple times until selecting new entity.
set-single-time: true

# Sets players' visibility length when selecting entities
# Put double value to modify visibility length.
# Recommended value: 4.0 ~
visibility-length-double: 5.0

# Sets velocity modifier, put Double value to modify velocity.
# If set to 1.0, the velocity would be so big that entity could move too far.
# Recommended value: 0.2 ~ 0.4
velocity-modifier-double: 0.3

# Sets maximum velocity
# Put Double value to set maximum velocity.
# Recommended value: 20 ~ 30
max-velocity-double: 24